# Generated by Django 5.2.4 on 2025-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_dislikes_postmodel_dis_likes_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikes',
            name='amount_of',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likes',
            name='amount_of',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
