# Generated by Django 5.2.4 on 2025-11-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postmodel_dis_likes_alter_postmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='dis_likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.dislikes'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.likes'),
        ),
    ]
