# Generated by Django 5.2.4 on 2025-11-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postmodel_dis_likes_remove_likes_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.postmodel'),
            preserve_default=False,
        ),
    ]
